### ISSUE TITLE
Check out openpgpjs

### ISSUE THREAD

**Issue by seancolyer** [elcodedocle/openpgpjs#1]
Hey just saw an alert about this project and wanted to give you a heads up to: https://github.com/openpgpjs/openpgpjs which provides a much more complete OpenPGP implementation than what you are basing this off of. FYI.

**Comment by elcodedocle** [comment]
Cool, I'll check it out. Thanks for the heads up :-) 

Hanewin's project is stable and has been tested through the years which is crucial on encryption utils but it is not maintained anymore and has not been for a long time. 

I've started using it packaged this way 4 years ago and I am very happy with the performance I am getting (quite impressive for a javascript browser app!) and the features it offers, though. 

I was planning to turn my packaging of it into a full js project so I can add a minified build (which is what I am using on production) to the composer dependency. That way I can retrieve it on my php projects using composer without the need for bower or any other nodejs tools. That was really the main reason why I published this code, but it is good to know there are other Hanewin based alternatives out there ;-)
